<?php
session_start();
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
$DATA=__DIR__.'/data/site.json'; $UPLOAD=__DIR__.'/uploads';
if(!is_dir($UPLOAD)) mkdir($UPLOAD,0755,true);
function cfg(){global $DATA; if(!file_exists($DATA)) return []; $d=json_decode(file_get_contents($DATA),true); return is_array($d)?$d:[];}
function savecfg($c){global $DATA; file_put_contents($DATA,json_encode($c,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}
function out($x,$code=200){http_response_code($code);header('Content-Type: application/json');echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
$action=$_GET['action']??'';
function upi_valid($u){return is_string($u)&&preg_match('/^[A-Za-z0-9._\-]{2,256}@[A-Za-z][A-Za-z0-9]{1,64}$/',$u)===1;}
function sync_upi(){$c=cfg();if(!empty($c['upiId'])&&upi_valid($c['upiId'])){$p=__DIR__.'/upi.txt';$cur=file_exists($p)?trim((string)file_get_contents($p)):'';if($cur!==$c['upiId'])@file_put_contents($p,$c['upiId']."\n",LOCK_EX);}}
if($action==='config'){sync_upi();out(cfg());}
if($action==='login'){ $in=json_decode(file_get_contents('php://input'),true)?:[]; require __DIR__.'/admin_config.php'; if(password_verify((string)($in['password']??''),ADMIN_PASSWORD_HASH)){$_SESSION['tenver_admin']=true;out(['ok'=>true]);} out(['ok'=>false,'error'=>'Invalid password'],401); }
if($action==='logout'){session_destroy();out(['ok'=>true]);}
if(empty($_SESSION['tenver_admin'])) out(['error'=>'Unauthorized'],401);
if($action==='change_password'){ $in=json_decode(file_get_contents('php://input'),true)?:[];$new=(string)($in['password']??'');if(strlen($new)<8)out(['error'=>'Password must be at least 8 characters'],400);$path=__DIR__.'/admin_config.php';$txt=file_get_contents($path);$hash=password_hash($new,PASSWORD_DEFAULT);$txt=preg_replace("/const ADMIN_PASSWORD_HASH = '[^']*';/","const ADMIN_PASSWORD_HASH = '$hash';",$txt);file_put_contents($path,$txt,LOCK_EX);out(['ok'=>true]); }
if($action==='save'){ $in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))out(['error'=>'Invalid data'],400);$old=cfg();$allowed=['settings','theme','homeBanners','detailBanner','offerTicker','cartTicker','mysteryImage','paymentQr','products','site','navRightLogo','navLeftLogo','brandLogo','productBrand','returningOffer','paytmStatus'];foreach($allowed as $k)if(array_key_exists($k,$in))$old[$k]=$in[$k];if(array_key_exists('upiId',$in)){$u=trim((string)$in['upiId']);if(!upi_valid($u))out(['error'=>'UPI ID galat hai (example: name@bank)'],400);if(file_put_contents(__DIR__.'/upi.txt',$u."\n",LOCK_EX)===false)out(['error'=>'upi.txt save nahi hua'],500);$old['upiId']=$u;}if(!isset($old['returningOffer'])||!is_array($old['returningOffer']))$old['returningOffer']=['enabled'=>true,'percent'=>20,'resetSeconds'=>6,'message'=>'Hi Customer, Welcome Back! Our Price Increased 20% Due to High Demand.','label'=>'Returning Customer Price','animation'=>true];$old['returningOffer']['enabled']=!empty($old['returningOffer']['enabled']);$old['returningOffer']['percent']=max(0,(float)($old['returningOffer']['percent']??20));$old['returningOffer']['resetSeconds']=max(2,(int)($old['returningOffer']['resetSeconds']??6));$old['returningOffer']['message']=(string)($old['returningOffer']['message']??'Hi Customer, Welcome Back! Our Price Increased 20% Due to High Demand.');$old['returningOffer']['label']=(string)($old['returningOffer']['label']??'Returning Customer Price');$old['returningOffer']['animation']=!empty($old['returningOffer']['animation']);if(!isset($old['paytmStatus'])||!in_array($old['paytmStatus'],['available','unavailable'],true))$old['paytmStatus']='unavailable';savecfg($old);out(['ok'=>true,'config'=>$old]); }
if($action==='upload'&&$_SERVER['REQUEST_METHOD']==='POST'){if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)out(['error'=>'Upload failed'],400);$f=$_FILES['file'];if($f['size']>8*1024*1024)out(['error'=>'Max 8MB'],400);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];if(!isset($allowed[$mime]))out(['error'=>'Only JPG, PNG, WEBP or GIF'],400);$name='img_'.bin2hex(random_bytes(8)).'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],$UPLOAD.'/'.$name))out(['error'=>'Could not save'],500);out(['ok'=>true,'url'=>'uploads/'.$name]);}
if($action==='import_product'&&$_SERVER['REQUEST_METHOD']==='POST'){try{require __DIR__.'/import_lib.php';imp_handle($UPLOAD);}catch(Throwable $e){out(['ok'=>false,'error'=>'Importer error: '.$e->getMessage()],500);}}
out(['error'=>'Unknown action'],404);
?>
